// Mocks generated by Mockito 5.4.4 from annotations
// in article_app/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:article_app/src/data/repositories/article_repository.dart'
    as _i2;
import 'package:article_app/src/domain/entities/article.dart' as _i5;
import 'package:article_app/src/domain/entities/fetch_article.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeArticleRepository_0 extends _i1.SmartFake
    implements _i2.ArticleRepository {
  _FakeArticleRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FetchArticles].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchArticles extends _i1.Mock implements _i3.FetchArticles {
  MockFetchArticles() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ArticleRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeArticleRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ArticleRepository);

  @override
  _i4.Future<List<_i5.Article>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Article>>.value(<_i5.Article>[]),
      ) as _i4.Future<List<_i5.Article>>);
}
